### ISSUE TITLE
This isn't really a website testing zone.

### ISSUE THREAD

**Issue by nandantumu** [team178/website-testing#1]
I think we might be able to use Git Submodules to clone the site into this repo. We can then make edits here without affecting the live site.
[Here's a helpful Git tutorial on the subject](http://git-scm.com/book/en/v2/Git-Tools-Submodules)

**Comment by TJScalzo** [comment]
@nt1st I'm not quite sure if this would work. Right now, this repository shows up as a single page on the website at [farmingtonrobofics.org/website-testing](http://farmingtonrobotics.org/website-testing/) While we can use it to test single pages, hosting an entirely separate version of the website isn't possible right now. We could use submodules to merge changes in this repository into the website's; however, we wouldn't be able to display the entire website or this repository (unless we get a separate domain somewhere).

BTW: @gluxon might also be able to help with doing what you're suggesting.

**Comment by gisellegk** [comment]
So I only skimmed it a bit, but it sounds like submodules would be for a separate project that is part of a bigger project.... not sure how that would help us in this case.

I mean we could literally make a copy of the website in this repo, make changes here, and then copy changes into the main repo, but I don't see how that would help much. I think we'd be better off having students fork the main repo if we want them to work in a separate repository and just have people put in pull requests.

Honestly, I don't think we even need this repository. I don't really see need to modify our current workflow at all.

**Comment by gisellegk** [comment]
One thing a submodule might be useful for would be making the Hour of Code site separate from the main site? and anything of similar nature, like if we were to make a Jr. FLL Expo landing page sort of thing for that event. Stuff that's pretty significantly different from our team's website but still related I guess.

**Comment by TJScalzo** [comment]
@gisellegk that's basically the same conclusion I came to. However, I feel like this repository could be used for testing and storing ideas and features that we later implement onto the main site. (Like the sponsors bar at the bottom of the page or the Twitter widget that I found.) Rather than testing/hosting the entire site in here it should be used for small, specific things.

**Comment by gisellegk** [comment]
@TJScalzo What would be the advantage of doing that over using our /test pages? One pro for sticking with /test is that we'd be able to design stuff that works with the infrastructure that we have set up already (like templates/{{includes}}, stuff in main.css and other files that interact with what we add to the website)

**Comment by gluxon** [comment]
I'll chime in, but @gisellegk and @TJScalzo have pretty much covered everything. In my experience, git submodules are generally used for project dependencies. An example would be if you had a JavaScript library and it was being constantly updated on a git repository. Then a submodule would be useful to keep that up to date.

> We can then make edits here without affecting the live site.

If the goal is to make edits to `website-testing` without affecting the live site, that should already be possible.

> Honestly, I don't think we even need this repository. I don't really see need to modify our current workflow at all.

I kind of agree with that. I created this website-testing repository because I figured if people were going to directly edit code files on GitHub.com, doing it to this repository would be much better than on the main repository. Using /test pages accomplishes the same thing.

Even better would be to use branches and a local Jekyll installation when developing in-progress work, which looks like you guys have been doing as well.

> One thing a submodule might be useful for would be making the Hour of Code site separate from the main site?
> Sounds great.

**Comment by gisellegk** [comment]
> Even better would be to use branches and a local Jekyll installation when developing in-progress work, which looks like you guys have been doing as well.

That _is_ our current workflow right now. The /test pages are useful for showing off progress at wrap-up. :+1:

**Comment by gluxon** [comment]
> That is our current workflow right now. The /test pages are useful for showing off progress at wrap-up. :+1: 

Awesomeness...

**Comment by TJScalzo** [comment]
I agree completely with @gluxon and @gisellegk. I think our workflow works wonderfully for us. I think this repository can still exist, if not as a testing place for the entire site, then as a sandbox area for trying out features (like what I've been doing).

**Comment by gisellegk** [comment]
sounds cool to me :grin:

**Comment by nandantumu** [comment]
That sounds reasonable. I wasn't aware of the complete workflow. My worry
was that new commits were going straight to the live site without a quality
check, something that could cause problems. As long as that isn't
happening, I'm good. I was simply questioning the utility of this
repository.
